### ISSUE TITLE
chatbot run issue

### ISSUE THREAD

**Issue by babhlu24** [LearnCodeWithDurgesh/chatbot#1]
Traceback (most recent call last):
  File "C:/Users/bablu/PycharmProjects/chatbot/main.py", line 4, in <module>
    bot = ChatBot("My Bot")
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\chatterbot\storage\storage_adapter.py", line 21, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\chatterbot\tagging.py", line 13, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\bablu\PycharmProjects\chatbot\venv\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Process finished with exit code 1

**Comment by Sumay234** [comment]
Good how can i practice it or make it by my own
